# Generated by Django 3.1.7 on 2021-03-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0002_delete_empproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rreceivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'epidemic receivers',
                'verbose_name_plural': '2. Người nhận báo cáo',
            },
        ),
    ]
