# Generated by Django 3.1.7 on 2021-05-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0003_rreceivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='epidamic',
            name='authkind',
            field=models.CharField(choices=[('C', 'Đã khai báo với chính quyền'), ('K', 'Chưa khai báo với chính quền')], default='C', max_length=1, verbose_name='Bạn đã khai báo ytế ?'),
        ),
    ]
