# Generated by Django 3.1.7 on 2021-05-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0004_epidamic_authkind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epidamic',
            name='etemp',
            field=models.FloatField(default=36.6, max_length=5, verbose_name='Thân nhiệt ?'),
        ),
    ]
