# Generated by Django 3.1.7 on 2021-05-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0005_auto_20210503_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epidamic',
            name='remarks',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Ghi chú, Trong vòng 14 ngày qua, Anh/Chị có đến tỉnh/thành phố, quốc gia/vùng lãnh thổ nào (Có thể đi qua nhiều nơi)'),
        ),
    ]
