# Generated by Django 3.1.7 on 2021-05-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0006_auto_20210503_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epidamic',
            name='bkind',
            field=models.CharField(choices=[('C', 'Có'), ('K', 'Không')], default='K', max_length=1, verbose_name='Trong 14 ngày qua anh/chị có tiếp xúc với người bệnh/hoặc người nghi nhiễm mắc Covid-19 hay không?'),
        ),
        migrations.AlterField(
            model_name='epidamic',
            name='remarks',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Trong vòng 14 ngày qua, Anh/Chị có đến tỉnh/thành phố, quốc gia/vùng lãnh thổ nào (Có thể đi qua nhiều nơi)'),
        ),
    ]
