# Generated by Django 3.1.7 on 2021-05-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0009_auto_20210528_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epidamic',
            name='authkind',
        ),
        migrations.AlterField(
            model_name='epidamic',
            name='bkind',
            field=models.CharField(choices=[('C', 'Yes'), ('K', 'No')], default='K', max_length=1, verbose_name='Trong 14 ngày qua anh/chị có tiếp xúc với người bệnh hoặc người nghi nhiễm mắc Covid-19 hay không/Contact to suspicious CV19 patient ?'),
        ),
    ]
