# Generated by Django 3.1.7 on 2021-03-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ntboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên tài liệu')),
                ('dateissue', models.DateField(blank=True, null=True, verbose_name='Ngày ban hành')),
                ('docfile', models.FileField(default=None, upload_to='documents/%Y/%m/%d', verbose_name='Link download')),
            ],
            options={
                'verbose_name': 'notice board',
                'verbose_name_plural': '4. Các vấn đề khác',
            },
        ),
        migrations.CreateModel(
            name='prdbd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên tài liệu')),
                ('dateissue', models.DateField(blank=True, null=True, verbose_name='Ngày ban hành')),
                ('docfile', models.FileField(default=None, upload_to='documents/%Y/%m/%d', verbose_name='Link download')),
            ],
            options={
                'verbose_name': 'Production notice',
                'verbose_name_plural': '3. Sản xuất',
            },
        ),
        migrations.CreateModel(
            name='qualitybd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên tài liệu')),
                ('dateissue', models.DateField(blank=True, null=True, verbose_name='Ngày ban hành')),
                ('docfile', models.FileField(default=None, upload_to='documents/%Y/%m/%d', verbose_name='Link download')),
            ],
            options={
                'verbose_name': 'Quality notice',
                'verbose_name_plural': '2. Chất lượng',
            },
        ),
        migrations.CreateModel(
            name='safetybd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên tài liệu')),
                ('dateissue', models.DateField(blank=True, null=True, verbose_name='Ngày ban hành')),
                ('docfile', models.FileField(default=None, upload_to='documents/%Y/%m/%d', verbose_name='Link download')),
            ],
            options={
                'verbose_name': 'Safety notice',
                'verbose_name_plural': '1. An toàn & 5S',
            },
        ),
    ]
