# Generated by Django 3.1.7 on 2021-04-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0002_vnspgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='vnspgallery',
            name='hlink',
            field=models.URLField(blank=True, null=True, verbose_name='Thông tin chi tiết'),
        ),
    ]
