# Generated by Django 3.1.7 on 2021-04-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0003_vnspgallery_hlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetybd',
            name='docfile2',
            field=models.FileField(default=None, upload_to='documents/%Y/%m/%d', verbose_name='Link download 2'),
        ),
        migrations.AlterField(
            model_name='safetybd',
            name='docfile',
            field=models.FileField(default=None, upload_to='documents/%Y/%m/%d', verbose_name='Link download 1'),
        ),
    ]
