# Generated by Django 3.1.7 on 2021-04-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0004_auto_20210429_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='prdbd',
            name='docfile2',
            field=models.FileField(default=None, upload_to='documents/%Y/%m/%d', verbose_name='Link download 2'),
        ),
        migrations.AddField(
            model_name='qualitybd',
            name='docfile2',
            field=models.FileField(default=None, upload_to='documents/%Y/%m/%d', verbose_name='Link download 2'),
        ),
    ]
