# Generated by Django 3.1.7 on 2021-03-21 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pvm',
            options={'verbose_name': 'PVM', 'verbose_name_plural': '1. Philosophy - Vision - Mission'},
        ),
    ]
