# Generated by Django 3.1.7 on 2021-03-21 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20210321_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': '4. FAQ'},
        ),
    ]
