# Generated by Django 3.1.7 on 2021-03-21 14:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20210321_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wpost',
            options={'verbose_name': 'WPOST', 'verbose_name_plural': '3. Working Position'},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answ',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='idate',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='quest',
        ),
        migrations.AddField(
            model_name='faq',
            name='topic',
            field=models.CharField(default=None, max_length=255, verbose_name='Topic'),
        ),
        migrations.CreateModel(
            name='FAQDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.TextField(default=None, max_length=500, verbose_name='Question')),
                ('answ', models.TextField(default=None, max_length=500, verbose_name='Answer')),
                ('idate', models.DateField(default=django.utils.timezone.now, verbose_name='Issued date')),
                ('topic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.faq', verbose_name='Topic')),
            ],
            options={
                'verbose_name': 'Q in T',
                'verbose_name_plural': 'Question in Topic',
            },
        ),
    ]
