# Generated by Django 3.1.7 on 2021-03-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20210321_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'frequently questioned answers', 'verbose_name_plural': '4. FAQ'},
        ),
        migrations.AlterModelOptions(
            name='faqdetail',
            options={'verbose_name': 'question in the topic', 'verbose_name_plural': 'Question in Topic'},
        ),
        migrations.AlterModelOptions(
            name='ochart',
            options={'verbose_name': 'organization chart', 'verbose_name_plural': '2. Organization Chart'},
        ),
        migrations.AlterModelOptions(
            name='set',
            options={'verbose_name': 'setting', 'verbose_name_plural': '5. Setting'},
        ),
        migrations.AlterModelOptions(
            name='wpost',
            options={'verbose_name': 'working position', 'verbose_name_plural': '3. Working Position'},
        ),
    ]
