# Generated by Django 3.1.7 on 2021-03-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20210321_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqdetail',
            name='idate',
        ),
    ]
