# Generated by Django 3.1.7 on 2021-03-28 00:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_remove_faqdetail_idate'),
    ]

    operations = [
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.TextField(default=None, max_length=500, verbose_name='Question')),
                ('answ', models.TextField(default=None, max_length=500, verbose_name='Answer')),
                ('idate', models.DateField(default=django.utils.timezone.now, verbose_name='Issued date')),
            ],
            options={
                'verbose_name': 'question in the topic',
                'verbose_name_plural': '5. Hỏi - Đáp',
            },
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'frequently questioned answers', 'verbose_name_plural': '4. Câu hỏi thường gặp'},
        ),
        migrations.AlterModelOptions(
            name='ochart',
            options={'verbose_name': 'organization chart', 'verbose_name_plural': '2. Sơ đồ tổ chức'},
        ),
        migrations.AlterModelOptions(
            name='set',
            options={'verbose_name': 'setting', 'verbose_name_plural': '6. Setting'},
        ),
        migrations.AlterModelOptions(
            name='wpost',
            options={'verbose_name': 'working position', 'verbose_name_plural': '3. Vị trí việc làm'},
        ),
    ]
