# Generated by Django 3.1.7 on 2021-03-28 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20210328_0707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'frequently questioned & answers', 'verbose_name_plural': '4. Câu hỏi thường gặp'},
        ),
        migrations.AlterModelOptions(
            name='qna',
            options={'verbose_name': 'question & answer', 'verbose_name_plural': '5. Hỏi - Đáp'},
        ),
    ]
