# Generated by Django 3.1.7 on 2021-03-28 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20210328_0709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pvm',
            options={'verbose_name': 'Philosophy - Vision - Mission', 'verbose_name_plural': '1. Triết lý - Tầm nhìn - Sứ mệnh - Giá trị cốt lõi'},
        ),
    ]
