# Generated by Django 3.1.7 on 2021-03-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20210328_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='fa',
        ),
        migrations.RemoveField(
            model_name='set',
            name='fb',
        ),
        migrations.AddField(
            model_name='set',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='set',
            name='fname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full name'),
        ),
    ]
