# Generated by Django 3.1.7 on 2021-03-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20210328_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='answ',
            field=models.TextField(default=None, max_length=500, verbose_name='Câu trả lời'),
        ),
        migrations.AlterField(
            model_name='qna',
            name='quest',
            field=models.TextField(default=None, max_length=500, verbose_name='Câu hỏi'),
        ),
    ]
