# Generated by Django 3.1.7 on 2021-03-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20210328_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='answ',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Câu trả lời'),
        ),
    ]
