# Generated by Django 3.1.7 on 2021-03-18 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='s360d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comment')),
                ('remarks', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Remarks')),
                ('idemp', models.ForeignKey(default=None, max_length=15, on_delete=django.db.models.deletion.CASCADE, to='eprofile.efile', verbose_name='Số ID')),
            ],
            options={
                'verbose_name': '360 survey',
                'verbose_name_plural': '3. 360 degree survey',
            },
        ),
        migrations.CreateModel(
            name='cotrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctyear', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên gọi, survey name')),
                ('ctremarks', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Ghi chú')),
                ('docfile', models.FileField(blank=True, default=None, null=True, upload_to='documents/%Y/%m/%d', verbose_name='Hướng dẫn chi tiết')),
                ('mempic', models.ImageField(blank=True, null=True, upload_to='comtrip', verbose_name='Ảnh thành viên, hoạt động..')),
                ('jkind', models.CharField(choices=[('C', 'Có tham gia'), ('K', 'Không tham gia')], default='K', max_length=1, verbose_name='Bạn có đăng ký tham gia chương trình này không ?')),
                ('feedbacks', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Thông tin phản hồi.(Ví dụ: chất lượng, dịch vụ, kích thước đồng phục..)')),
                ('idemp', models.ForeignKey(default=None, max_length=15, on_delete=django.db.models.deletion.CASCADE, to='eprofile.efile', verbose_name='Số ID')),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': '1. Đăng ký du lịch, lễ hội, tiêm phòng, đồng phục..',
            },
        ),
        migrations.CreateModel(
            name='cotmem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mkid', models.CharField(choices=[('w', 'Vợ'), ('H', 'Chồng'), ('C', 'Con'), ('O', 'Khác')], default='W', max_length=1, null=True, verbose_name='Thành viên')),
                ('dob', models.DateField(null=True, verbose_name='Năm sinh')),
                ('fullname', models.CharField(max_length=180, null=True, verbose_name='Họ và tên')),
                ('mbremarks', models.CharField(blank=True, max_length=180, null=True, verbose_name='Ghi chú')),
                ('ctdid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.cotrip')),
            ],
            options={
                'verbose_name': 'family memeber',
                'verbose_name_plural': '2. Danh sách thành viên đi cùng (du lịch, lễ hội..)',
            },
        ),
    ]
