# Generated by Django 3.1.7 on 2021-03-19 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotmem',
            options={'verbose_name': 'family memeber', 'verbose_name_plural': '2. Danh sách người nhà đi cùng (du lịch, lễ hội..)'},
        ),
    ]
