# Generated by Django 3.1.7 on 2021-03-19 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210319_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotmem',
            name='ctdid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.cotrip', verbose_name='ID'),
        ),
    ]
