# Generated by Django 3.1.7 on 2021-03-31 15:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eprofile', '0002_efile_lockerno'),
        ('survey', '0003_auto_20210319_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s360d',
            options={'verbose_name': '360 survey', 'verbose_name_plural': '4. 360 degree survey'},
        ),
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctyear', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên gọi, survey name')),
                ('ctremarks', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Ghi chú')),
                ('docfile', models.FileField(blank=True, default=None, null=True, upload_to='documents/%Y/%m/%d', verbose_name='Hướng dẫn chi tiết')),
                ('answertime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời điểm trả lời')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Hạn trả lời')),
                ('mempic', models.ImageField(blank=True, null=True, upload_to='comtrip', verbose_name='Ảnh thành viên, hoạt động..')),
                ('jkind', models.CharField(choices=[('A', 'Đáp án A'), ('B', 'Đáp án B'), ('C', 'Đáp án C'), ('D', 'Đáp án D'), ('E', 'Đáp án E'), ('F', 'Đáp án F')], default='A', max_length=1, verbose_name='Câu trả lời của bạn là ?')),
                ('idemp', models.ForeignKey(default=None, max_length=15, on_delete=django.db.models.deletion.CASCADE, to='eprofile.efile', verbose_name='Số ID')),
            ],
            options={
                'verbose_name': 'quiz',
                'verbose_name_plural': '3. Đố vui - Có thưởng',
            },
        ),
    ]
