# Generated by Django 3.1.7 on 2021-03-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20210331_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='jkind',
            field=models.CharField(blank=True, choices=[('A', 'Đáp án A'), ('B', 'Đáp án B'), ('C', 'Đáp án C'), ('D', 'Đáp án D'), ('E', 'Đáp án E'), ('F', 'Đáp án F')], default='', max_length=1, null=True, verbose_name='Câu trả lời của bạn'),
        ),
    ]
