# Generated by Django 3.1.7 on 2021-04-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20210401_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotrip',
            name='ctremarks',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='ctremarks',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Ghi chú, câu hỏi'),
        ),
    ]
