# Generated by Django 3.1.7 on 2021-04-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20210401_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answertime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Thời điểm trả lời'),
        ),
    ]
