# Generated by Django 3.1.7 on 2021-04-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20210401_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='subanswer',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Đáp án phụ'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='ctremarks',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Câu hỏi'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='jkind',
            field=models.CharField(blank=True, choices=[('A', 'Đáp án A'), ('B', 'Đáp án B'), ('C', 'Đáp án C'), ('D', 'Đáp án D'), ('E', 'Đáp án E'), ('F', 'Đáp án F')], default='', max_length=1, null=True, verbose_name='Đáp án'),
        ),
    ]
