# Generated by Django 3.1.7 on 2021-04-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20210402_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='docfile',
            field=models.FileField(blank=True, default=None, null=True, upload_to='documents/%Y/%m/%d', verbose_name='Link tới doc, clip'),
        ),
    ]
