# Generated by Django 3.1.7 on 2021-03-18 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eprofile', '0001_initial'),
        ('wage', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ts',
            unique_together={('idemp', 'tsday')},
        ),
    ]
