# Generated by Django 3.1.7 on 2021-03-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0002_auto_20210318_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='ts',
            name='AL',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phép năm'),
        ),
        migrations.AddField(
            model_name='ts',
            name='OTDay',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Overtime day'),
        ),
        migrations.AddField(
            model_name='ts',
            name='PP',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='PP'),
        ),
        migrations.AddField(
            model_name='ts',
            name='SI',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Bảo hiểm'),
        ),
        migrations.AddField(
            model_name='ts',
            name='UP',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='UP'),
        ),
    ]
