# Generated by Django 3.1.7 on 2021-03-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0003_auto_20210318_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ts',
            name='AL',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='AL'),
        ),
        migrations.AlterField(
            model_name='ts',
            name='SI',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='SI'),
        ),
    ]
